name: clang ASAN + cctest

on: [push, pull_request]

jobs:
  asan:
      runs-on: ubuntu-latest
      container: gengjiawen/node-build:2020-02-14
      env:
        CC: clang
        CXX: clang++
        LINK: clang++
      steps:
        - uses: actions/checkout@v2
        - name: Environment info
          run: npx envinfo
        - name: Configure
          run: ./configure --enable-asan
        - name: Build
          run: make -j2
        - name: Test
          env:
            ASAN_OPTIONS: new_delete_type_mismatch=0
          run:
            make -j2 cctest
