name: "Commit messages adheres to guidelines at https://goo.gl/p2fr5Q"

on: [pull_request_target]


jobs:
  lint-commit-message:
    runs-on: ubuntu-latest
    env:
      get_commits: git log --oneline PR_BASE..PR_HEAD | grep -v -e fixup -e squash | awk '{ print $1 }'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: cd tools/actions/ && npm install

      - name: Validate commit messages
        run: |
          cd tools/actions
          node --experimental-top-level-await validate-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
